# FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-devel 
FROM nvidia/cuda:11.2.0-cudnn8-devel-ubuntu18.04 
RUN apt-get update && apt-get install -y sudo pkg-config vim ffmpeg libsm6 libxext6 wget zip git curl
RUN curl -L -o /miniconda.sh -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh; chmod +x /miniconda.sh; ./miniconda.sh -b -p /opt/conda; export PATH=/opt/conda/bin:$PATH
# remember to write export PATH=/opt/conda/bin:$PATH into .bashrc
# cv2.cpython-[37|38|39]-x86_64-linux-gnu.so
WORKDIR /root

